### ISSUE TITLE
one more column 

### ISSUE THREAD

**Issue by zpliu1126** [inutano/pfastq-dump#1]
I used such command 
pfastq-dump -t 20 --split-files --gzip id_of_SRR

the out file with one more column
such like this 

@SRR1695192.1 1 HWI-ST979:238:D1HW8ACXX:6:1101:1746:2121 length=101
CAGTGGGGTTCTGCCCAAGTGATCGCATCACAGTTCCCAACTCCTTGGTAGTAATGCAACCATCTCCATCCTTGAGATCGGAAGAGCACACGTCTGAACTC

but
i used fastq-dump --split-files --gzip id_of_SRR

@SRR1695192.1 HWI-ST979:238:D1HW8ACXX:6:1101:1746:2121 length=101
CAGTGGGGTTCTGCCCAAGTGATCGCATCACAGTTCCCAACTCCTTGGTAGTAATGCAACCATCTCCATCCTTGAGATCGGAAGAGCACACGTCTGAACTC

and this issues onle appears in pairs_sequencing_files

I want to know if this issues has any effect on the future ！

**Comment by inutano** [comment]
Hi @zpliu1126, thanks for using my implementation. I've tested with the same data SRR1695192, but could not reproduce what you got. I got the same lines as following without another "1" in the read name lines:

```
inutano@Sara ~/repos/sandbox/pfastq-dump-test/SRR1695192 🐣   13:47:27 gunzip -c non-parallel/SRR1695192_1.fastq.gz|head -4
@SRR1695192.1 HWI-ST979:238:D1HW8ACXX:6:1101:1746:2121 length=101
CAGTGGGGTTCTGCCCAAGTGATCGCATCACAGTTCCCAACTCCTTGGTAGTAATGCAACCATCTCCATCCTTGAGATCGGAAGAGCACACGTCTGAACTC
+SRR1695192.1 HWI-ST979:238:D1HW8ACXX:6:1101:1746:2121 length=101
@@BDFFADHFFFHIJJJJIHHIJJGIIJJJJJGGHHIHGIJJJJJJIIFHHFHIJIJIIJIJJJFHHGHHFFFFFFDCEDDDDBBDDDDDDBBBDBCACAC
```

```
inutano@Sara ~/repos/sandbox/pfastq-dump-test/SRR1695192 🐣   13:47:16 gunzip -c parallel/SRR1695192_1.fastq.gz|head -4
@SRR1695192.1 HWI-ST979:238:D1HW8ACXX:6:1101:1746:2121 length=101
CAGTGGGGTTCTGCCCAAGTGATCGCATCACAGTTCCCAACTCCTTGGTAGTAATGCAACCATCTCCATCCTTGAGATCGGAAGAGCACACGTCTGAACTC
+SRR1695192.1 HWI-ST979:238:D1HW8ACXX:6:1101:1746:2121 length=101
@@BDFFADHFFFHIJJJJIHHIJJGIIJJJJJGGHHIHGIJJJJJJIIFHHFHIJIJIIJIJJJFHHGHHFFFFFFDCEDDDDBBDDDDDDBBBDBCACAC
```

But I confirmed I get a similar id line with another data, for example SRR1274307:

```
inutano@Sara ~/repos/sandbox/pfastq-dump-test/SRR1274307 🐣   13:48:13 gunzip -c non-parallel/SRR1274307_1.fastq.gz|head -4
@SRR1274307.1 1 length=25
ATGGCTCACTGCAGCCTTGACTTTC
+SRR1274307.1 1 length=25
AAA?ABBBDEEDDDDEGGGFGGIIH
```

```
inutano@Sara ~/repos/sandbox/pfastq-dump-test/SRR1274307 🐣   13:50:32 gunzip -c parallel/SRR1274307_1.fastq.gz|head -4
@SRR1274307.1 1 length=25
ATGGCTCACTGCAGCCTTGACTTTC
+SRR1274307.1 1 length=25
AAA?ABBBDEEDDDDEGGGFGGIIH
```

But the lines are same with both fastq-dump and pfastq-dump.

So I suppose you got lines of different column numbers just because they are from different data. Basically pfastq-dump is just a simple wrapper that runs multiple fasts-dump with the same arguments, so the final output files should be identical - you can check the md5 checksum values with unzipped fastq files, since the pfastq-dump merges multiple gripped files as one final output which makes different checksum values for gzipped files from parallel/non-parallel. 

If you got a case that different lines from the same data dumped by fastq-dump and pfastq-dump, it may be a problem of your data and your version of fastq-dump.
